FROM golang:1.20-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./handlers ./handlers
COPY ./utils ./utils
COPY ./models ./models
COPY ./public ./public
COPY ./credentials.json ./
COPY ./main.go ./

RUN go build -o /app/wordfun

ENTRYPOINT ["/app/wordfun"]